// const data = [
//   {
//     id: 1,
//     title: "this is title of the page",
//     text: "This is text of the page",
//     associatedNumber: 500, // price, views, etc.
//     language: "urdu",
//     region: "PK",
//     lastUpdate:
//       "put something of your choice so that it can easily be filtered by (past 24hrs, past week, past month)",
//     siteOrDomain: "https://fbise.edu.pk",
//     termsAppearing: "title", // anywhere, title, text, URL
//   },
// ];
const data = [
  {
    id: 1,
    title: "Complete Guide to Federal Board Examinations 2025",
    text: "Everything you need to know about FBISE exams, including schedules, syllabi, and preparation tips for intermediate and matriculation students.",
    associatedNumber: 1250,
    language: "english",
    region: "PK",
    lastUpdate: "2026-02-01T08:30:00Z",
    siteOrDomain: "https://fbise.edu.pk",
    termsAppearing: "title",
  },
  {
    id: 2,
    title: "کراچی میں بہترین ریستوران",
    text: "کراچی کے مشہور کھانوں اور ریستورانوں کی تفصیلی معلومات۔ یہاں آپ کو پاکستانی کھانوں کی بہترین جگہیں ملیں گی۔",
    associatedNumber: 450,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-31T14:20:00Z",
    siteOrDomain: "https://karachifood.pk",
    termsAppearing: "anywhere",
  },
  {
    id: 3,
    title: "Top 10 JavaScript Frameworks in 2026",
    text: "A comprehensive analysis of the most popular JavaScript frameworks including React, Vue, Angular, and emerging technologies.",
    associatedNumber: 8900,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-30T10:15:00Z",
    siteOrDomain: "https://devcentral.com",
    termsAppearing: "text",
  },
  {
    id: 4,
    title: "لاہور کی تاریخی عمارات",
    text: "لاہور کی قدیم اور تاریخی عمارتوں کے بارے میں معلومات، بادشاہی مسجد، لاہور قلعہ اور شالیمار باغ کی تفصیل۔",
    associatedNumber: 3200,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-29T16:45:00Z",
    siteOrDomain: "https://lahoreheritage.pk",
    termsAppearing: "title",
  },
  {
    id: 5,
    title: "London Weather Forecast Next Week",
    text: "Detailed weather predictions for London showing temperatures, rainfall probability, and wind conditions for the upcoming seven days.",
    associatedNumber: 15600,
    language: "english",
    region: "UK",
    lastUpdate: "2026-02-01T06:00:00Z",
    siteOrDomain: "https://ukweather.co.uk",
    termsAppearing: "URL",
  },
  {
    id: 6,
    title: "Best Python Libraries for Data Science",
    text: "Explore essential Python libraries like NumPy, Pandas, Matplotlib, and Scikit-learn for data analysis and machine learning projects.",
    associatedNumber: 7200,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-28T09:30:00Z",
    siteOrDomain: "https://datasciencehub.com",
    termsAppearing: "anywhere",
  },
  {
    id: 7,
    title: "اسلام آباد کے سیاحتی مقامات",
    text: "دارالحکومت اسلام آباد کے خوبصورت سیاحتی مقامات جیسے فیصل مسجد، دمن کوہ، اور راول جھیل کی معلومات۔",
    associatedNumber: 2100,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-27T11:20:00Z",
    siteOrDomain: "https://visitislamabad.pk",
    termsAppearing: "text",
  },
  {
    id: 8,
    title: "Manchester United Latest Transfer News",
    text: "Breaking news about Manchester United's transfer activities, including rumored signings and player departures for the current season.",
    associatedNumber: 23400,
    language: "english",
    region: "UK",
    lastUpdate: "2026-02-01T07:45:00Z",
    siteOrDomain: "https://footballnews.co.uk",
    termsAppearing: "title",
  },
  {
    id: 9,
    title: "Healthy Breakfast Recipes",
    text: "Quick and nutritious breakfast ideas including smoothie bowls, overnight oats, avocado toast, and protein-packed egg dishes.",
    associatedNumber: 5800,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-26T08:00:00Z",
    siteOrDomain: "https://healthyeating.com",
    termsAppearing: "anywhere",
  },
  {
    id: 10,
    title: "پشاور کی ثقافت اور روایات",
    text: "پشاور کی منفرد پختون ثقافت، زبان، کھانے، اور روایتی رسومات کی تفصیلی معلومات۔",
    associatedNumber: 1800,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-25T13:30:00Z",
    siteOrDomain: "https://peshawarnews.pk",
    termsAppearing: "URL",
  },
  {
    id: 11,
    title: "Cryptocurrency Market Analysis 2026",
    text: "In-depth analysis of Bitcoin, Ethereum, and altcoin markets with price predictions and investment strategies.",
    associatedNumber: 12500,
    language: "english",
    region: "US",
    lastUpdate: "2026-02-01T05:30:00Z",
    siteOrDomain: "https://cryptoinsights.com",
    termsAppearing: "text",
  },
  {
    id: 12,
    title: "Cambridge University Admission Guide",
    text: "Complete information about Cambridge University admissions, entry requirements, application process, and scholarship opportunities.",
    associatedNumber: 9400,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-31T10:15:00Z",
    siteOrDomain: "https://cambridgeinfo.co.uk",
    termsAppearing: "title",
  },
  {
    id: 13,
    title: "کوئٹہ کے مشہور کھانے",
    text: "کوئٹہ کے روایتی اور مشہور کھانوں کی فہرست، سجی، کہوا، اور بلوچی پلاؤ کی تفصیل۔",
    associatedNumber: 980,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-24T15:40:00Z",
    siteOrDomain: "https://balochfood.pk",
    termsAppearing: "anywhere",
  },
  {
    id: 14,
    title: "New York Real Estate Trends 2026",
    text: "Housing market analysis for New York City including property prices, rental rates, and investment opportunities in different boroughs.",
    associatedNumber: 34500,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-30T12:00:00Z",
    siteOrDomain: "https://nyrealty.com",
    termsAppearing: "URL",
  },
  {
    id: 15,
    title: "Birmingham Shopping Centers Guide",
    text: "A comprehensive guide to shopping malls and retail centers in Birmingham, featuring the best stores and dining options.",
    associatedNumber: 6700,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-29T09:20:00Z",
    siteOrDomain: "https://shopbirmingham.co.uk",
    termsAppearing: "text",
  },
  {
    id: 16,
    title: "ملتان کے آم کی اقسام",
    text: "ملتان کے مشہور آموں کی مختلف اقسام جیسے چونسا، سندھڑی، انور راٹول اور ان کی خصوصیات۔",
    associatedNumber: 1450,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-23T14:10:00Z",
    siteOrDomain: "https://multanmangoes.pk",
    termsAppearing: "title",
  },
  {
    id: 17,
    title: "Machine Learning Tutorial for Beginners",
    text: "Step-by-step guide to learning machine learning concepts, algorithms, and practical applications using Python.",
    associatedNumber: 11200,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-28T11:45:00Z",
    siteOrDomain: "https://learnml.com",
    termsAppearing: "anywhere",
  },
  {
    id: 18,
    title: "Liverpool FC Season Review",
    text: "Comprehensive review of Liverpool's performance this season including match highlights, player statistics, and tactical analysis.",
    associatedNumber: 18900,
    language: "english",
    region: "UK",
    lastUpdate: "2026-02-01T08:00:00Z",
    siteOrDomain: "https://lfcnews.co.uk",
    termsAppearing: "URL",
  },
  {
    id: 19,
    title: "فیصل آباد کی ٹیکسٹائل انڈسٹری",
    text: "فیصل آباد کی ٹیکسٹائل انڈسٹری کی تاریخ، موجودہ صورتحال اور مستقبل کے امکانات کی معلومات۔",
    associatedNumber: 2700,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-22T16:55:00Z",
    siteOrDomain: "https://faisalabadtextile.pk",
    termsAppearing: "text",
  },
  {
    id: 20,
    title: "California Wildfires Prevention Tips",
    text: "Essential safety guidelines and prevention strategies for California residents to protect their homes from wildfires.",
    associatedNumber: 8600,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-27T07:30:00Z",
    siteOrDomain: "https://calfireinfo.com",
    termsAppearing: "title",
  },
  {
    id: 21,
    title: "Oxford Street Shopping Experience",
    text: "Explore the famous Oxford Street in London with its luxury brands, flagship stores, and unique shopping experiences.",
    associatedNumber: 14300,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-31T13:25:00Z",
    siteOrDomain: "https://oxfordstreet.co.uk",
    termsAppearing: "anywhere",
  },
  {
    id: 22,
    title: "راولپنڈی کی پبلک ٹرانسپورٹ",
    text: "راولپنڈی میں میٹرو بس، عام بسیں اور دیگر ٹرانسپورٹ کی سہولیات کی مکمل معلومات۔",
    associatedNumber: 1650,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-21T10:40:00Z",
    siteOrDomain: "https://rwptransit.pk",
    termsAppearing: "URL",
  },
  {
    id: 23,
    title: "Web Development Best Practices 2026",
    text: "Modern web development standards covering responsive design, accessibility, performance optimization, and security measures.",
    associatedNumber: 9800,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-30T14:50:00Z",
    siteOrDomain: "https://webdevpro.com",
    termsAppearing: "text",
  },
  {
    id: 24,
    title: "Edinburgh Festival Fringe Guide",
    text: "Complete guide to the world's largest arts festival featuring theatre, comedy, music, and cultural performances.",
    associatedNumber: 7800,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-26T12:15:00Z",
    siteOrDomain: "https://edinburghfest.co.uk",
    termsAppearing: "title",
  },
  {
    id: 25,
    title: "حیدرآباد کی بریانی کی تاریخ",
    text: "حیدرآباد کی مشہور بریانی کی تاریخ، بنانے کا طریقہ اور مشہور ریستورانوں کی معلومات۔",
    associatedNumber: 3400,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-20T09:25:00Z",
    siteOrDomain: "https://hyderabadbiryani.pk",
    termsAppearing: "anywhere",
  },
  {
    id: 26,
    title: "Texas BBQ Restaurant Reviews",
    text: "Authentic Texas barbecue joints reviewed with ratings, menu highlights, and tips for the best BBQ experience.",
    associatedNumber: 5600,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-29T08:40:00Z",
    siteOrDomain: "https://texasbbq.com",
    termsAppearing: "URL",
  },
  {
    id: 27,
    title: "Leeds United Match Highlights",
    text: "Latest match reports, goals, and analysis from Leeds United's recent games in the Championship.",
    associatedNumber: 12400,
    language: "english",
    region: "UK",
    lastUpdate: "2026-02-01T09:10:00Z",
    siteOrDomain: "https://leedsutd.co.uk",
    termsAppearing: "text",
  },
  {
    id: 28,
    title: "سکھر کی تاریخی اہمیت",
    text: "سکھر شہر کی تاریخی اہمیت، لنسڈاؤن برج اور دیگر تاریخی مقامات کی تفصیل۔",
    associatedNumber: 890,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-19T15:30:00Z",
    siteOrDomain: "https://sukkurhistory.pk",
    termsAppearing: "title",
  },
  {
    id: 29,
    title: "Florida Beach Vacation Destinations",
    text: "Top beach destinations in Florida including Miami Beach, Clearwater, and Key West with travel tips and activities.",
    associatedNumber: 16700,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-28T10:20:00Z",
    siteOrDomain: "https://floridabeaches.com",
    termsAppearing: "anywhere",
  },
  {
    id: 30,
    title: "Bristol Music Scene Overview",
    text: "Explore Bristol's vibrant music culture, featuring live venues, local bands, and upcoming concerts and festivals.",
    associatedNumber: 4900,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-31T11:40:00Z",
    siteOrDomain: "https://bristolmusic.co.uk",
    termsAppearing: "URL",
  },
  {
    id: 31,
    title: "گلگت بلتستان کے قدرتی مناظر",
    text: "گلگت بلتستان کے خوبصورت پہاڑ، جھیلیں اور وادیاں جیسے ہنزہ، نلتر اور سکردو کی معلومات۔",
    associatedNumber: 4200,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-18T13:50:00Z",
    siteOrDomain: "https://gilgitbeauty.pk",
    termsAppearing: "text",
  },
  {
    id: 32,
    title: "Cloud Computing Solutions for Businesses",
    text: "Enterprise cloud computing options including AWS, Azure, and Google Cloud with cost comparisons and migration strategies.",
    associatedNumber: 22100,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-30T09:05:00Z",
    siteOrDomain: "https://cloudenterprisetech.com",
    termsAppearing: "title",
  },
  {
    id: 33,
    title: "Newcastle City Center Attractions",
    text: "Discover Newcastle's top attractions including the Quayside, Grey Street, and the historic castle.",
    associatedNumber: 6200,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-27T14:30:00Z",
    siteOrDomain: "https://visitnewcastle.co.uk",
    termsAppearing: "anywhere",
  },
  {
    id: 34,
    title: "سیالکوٹ کی کھیلوں کی صنعت",
    text: "سیالکوٹ کی کھیلوں کے سامان کی صنعت، فٹ بال اور کرکٹ کے سامان کی تیاری کی معلومات۔",
    associatedNumber: 3100,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-17T11:10:00Z",
    siteOrDomain: "https://sialkotssports.pk",
    termsAppearing: "URL",
  },
  {
    id: 35,
    title: "Chicago Deep Dish Pizza Guide",
    text: "The ultimate guide to Chicago's famous deep dish pizza including the best pizzerias and their signature recipes.",
    associatedNumber: 7400,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-29T12:45:00Z",
    siteOrDomain: "https://chicagopizza.com",
    termsAppearing: "text",
  },
  {
    id: 36,
    title: "Sheffield Steel Industry History",
    text: "Historical overview of Sheffield's steel industry and its transformation into a modern manufacturing hub.",
    associatedNumber: 5300,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-26T10:55:00Z",
    siteOrDomain: "https://sheffieldsteel.co.uk",
    termsAppearing: "title",
  },
  {
    id: 37,
    title: "بہاولپور کے تاریخی محلات",
    text: "بہاولپور کے شاہی محلات، نور محل، درباڑ محل اور دیگر تاریخی عمارتوں کی تفصیل۔",
    associatedNumber: 1950,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-16T08:35:00Z",
    siteOrDomain: "https://bahawalpurpalaces.pk",
    termsAppearing: "anywhere",
  },
  {
    id: 38,
    title: "Boston Medical Research Centers",
    text: "Overview of leading medical research facilities and hospitals in Boston contributing to healthcare innovations.",
    associatedNumber: 28600,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-31T07:20:00Z",
    siteOrDomain: "https://bostonmedresearch.com",
    termsAppearing: "URL",
  },
  {
    id: 39,
    title: "Cardiff Bay Waterfront Development",
    text: "Information about Cardiff Bay's transformation, attractions, restaurants, and cultural venues along the waterfront.",
    associatedNumber: 8900,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-30T15:10:00Z",
    siteOrDomain: "https://cardiffbay.co.uk",
    termsAppearing: "text",
  },
  {
    id: 40,
    title: "جھنگ کی زراعت اور فصلیں",
    text: "جھنگ کی زرعی صنعت، اہم فصلیں جیسے گندم، چاول اور کپاس کی کاشت کی معلومات۔",
    associatedNumber: 1320,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-15T14:45:00Z",
    siteOrDomain: "https://jhangagriculture.pk",
    termsAppearing: "title",
  },
  {
    id: 41,
    title: "Seattle Coffee Shop Culture",
    text: "Explore Seattle's renowned coffee culture, from Starbucks origins to independent specialty coffee roasters.",
    associatedNumber: 9200,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-28T13:30:00Z",
    siteOrDomain: "https://seattlecoffee.com",
    termsAppearing: "anywhere",
  },
  {
    id: 42,
    title: "Southampton Port and Maritime Heritage",
    text: "History of Southampton's port, its role in maritime trade, and modern shipping operations.",
    associatedNumber: 11800,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-29T11:25:00Z",
    siteOrDomain: "https://southamptonport.co.uk",
    termsAppearing: "URL",
  },
  {
    id: 43,
    title: "مردان کی ثقافتی روایات",
    text: "مردان کی پختون ثقافت، روایتی رقص جیسے خٹک اور اتن کی تفصیل اور معلومات۔",
    associatedNumber: 780,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-14T12:20:00Z",
    siteOrDomain: "https://mardanculture.pk",
    termsAppearing: "text",
  },
  {
    id: 44,
    title: "Denver Ski Resort Recommendations",
    text: "Best ski resorts near Denver including Aspen, Vail, and Breckenridge with trail maps and accommodation options.",
    associatedNumber: 19500,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-31T08:50:00Z",
    siteOrDomain: "https://denverskiing.com",
    termsAppearing: "title",
  },
  {
    id: 45,
    title: "Nottingham Robin Hood Heritage",
    text: "Explore Nottingham's connection to the legendary Robin Hood, including historical sites and annual festivals.",
    associatedNumber: 6800,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-27T09:40:00Z",
    siteOrDomain: "https://robinhoodnotts.co.uk",
    termsAppearing: "anywhere",
  },
  {
    id: 46,
    title: "گوجرانوالہ کی صنعت اور تجارت",
    text: "گوجرانوالہ کی صنعتی ترقی، چینی مٹی کے برتن اور دیگر صنعتوں کی معلومات۔",
    associatedNumber: 2450,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-13T10:05:00Z",
    siteOrDomain: "https://gujranwalaindustry.pk",
    termsAppearing: "URL",
  },
  {
    id: 47,
    title: "Philadelphia Historic Landmarks",
    text: "Tour of Philadelphia's historic sites including Independence Hall, Liberty Bell, and Benjamin Franklin's legacy.",
    associatedNumber: 13700,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-30T11:15:00Z",
    siteOrDomain: "https://phillyhistory.com",
    termsAppearing: "text",
  },
  {
    id: 48,
    title: "Leicester Space Centre Activities",
    text: "Interactive exhibits and planetarium shows at the National Space Centre in Leicester for all ages.",
    associatedNumber: 5700,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-26T13:50:00Z",
    siteOrDomain: "https://leicesterspace.co.uk",
    termsAppearing: "title",
  },
  {
    id: 49,
    title: "ساہیوال کی ڈیری انڈسٹری",
    text: "ساہیوال کی دودھ کی صنعت، ساہیوال گائے کی نسل اور دودھ کی پیداوار کی معلومات۔",
    associatedNumber: 1590,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-12T15:55:00Z",
    siteOrDomain: "https://sahiwaldairy.pk",
    termsAppearing: "anywhere",
  },
  {
    id: 50,
    title: "San Francisco Tech Startup Ecosystem",
    text: "Overview of San Francisco's thriving startup scene, venture capital, and innovation hubs in Silicon Valley.",
    associatedNumber: 45200,
    language: "english",
    region: "US",
    lastUpdate: "2026-02-01T06:30:00Z",
    siteOrDomain: "https://sftechstartups.com",
    termsAppearing: "URL",
  },
  {
    id: 51,
    title: "Brighton Pier Entertainment Guide",
    text: "Everything happening at Brighton Pier including rides, arcades, restaurants, and seasonal events.",
    associatedNumber: 9700,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-31T12:35:00Z",
    siteOrDomain: "https://brightonpier.co.uk",
    termsAppearing: "text",
  },
  {
    id: 52,
    title: "شیخوپورہ کی زراعت",
    text: "شیخوپورہ کے علاقے میں کاشت ہونے والی فصلیں، کسانوں کی سہولیات اور زرعی ترقی۔",
    associatedNumber: 1120,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-11T09:40:00Z",
    siteOrDomain: "https://sheikhupurafarming.pk",
    termsAppearing: "title",
  },
  {
    id: 53,
    title: "Austin Live Music Venues",
    text: "Guide to Austin's famous live music scene, featuring top venues, upcoming concerts, and local artists.",
    associatedNumber: 8300,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-29T14:20:00Z",
    siteOrDomain: "https://austinlivemusic.com",
    termsAppearing: "anywhere",
  },
  {
    id: 54,
    title: "Plymouth Naval History Museum",
    text: "Discover Plymouth's rich naval heritage at the museum showcasing maritime artifacts and naval history.",
    associatedNumber: 4100,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-28T08:15:00Z",
    siteOrDomain: "https://plymouthnaval.co.uk",
    termsAppearing: "URL",
  },
  {
    id: 55,
    title: "جہلم کے تاریخی مقامات",
    text: "جہلم شہر کی تاریخی اہمیت، سکندر اعظم کی جنگ اور روہتاس قلعہ کی معلومات۔",
    associatedNumber: 1680,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-10T13:25:00Z",
    siteOrDomain: "https://jhelumhistory.pk",
    termsAppearing: "text",
  },
  {
    id: 56,
    title: "Portland Food Truck Scene",
    text: "Comprehensive guide to Portland's diverse food truck offerings, from gourmet burgers to international cuisines.",
    associatedNumber: 6900,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-31T10:45:00Z",
    siteOrDomain: "https://portlandfoodtrucks.com",
    termsAppearing: "title",
  },
  {
    id: 57,
    title: "York Minster Cathedral Tours",
    text: "Guided tours of the magnificent York Minster, one of the largest Gothic cathedrals in Northern Europe.",
    associatedNumber: 10200,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-30T07:50:00Z",
    siteOrDomain: "https://yorkminster.co.uk",
    termsAppearing: "anywhere",
  },
  {
    id: 58,
    title: "خانیوال کی کپاس کی فصل",
    text: "خانیوال میں کپاس کی کاشت، پیداوار اور کپاس سے متعلق صنعتوں کی معلومات۔",
    associatedNumber: 920,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-09T11:50:00Z",
    siteOrDomain: "https://khanewalcotton.pk",
    termsAppearing: "URL",
  },
  {
    id: 59,
    title: "Nashville Country Music History",
    text: "Explore Nashville's legacy as the home of country music, featuring the Grand Ole Opry and Country Music Hall of Fame.",
    associatedNumber: 12900,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-27T15:30:00Z",
    siteOrDomain: "https://nashvillecountry.com",
    termsAppearing: "text",
  },
  {
    id: 60,
    title: "Canterbury Cathedral Heritage Site",
    text: "Visit the historic Canterbury Cathedral, a UNESCO World Heritage site and center of English Christianity.",
    associatedNumber: 8600,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-29T13:05:00Z",
    siteOrDomain: "https://canterburycathedral.co.uk",
    termsAppearing: "title",
  },
  {
    id: 61,
    title: "کسور کی چمڑے کی صنعت",
    text: "کسور کی چمڑے کی صنعت، ٹینریاں اور چمڑے کی مصنوعات کی برآمد کی معلومات۔",
    associatedNumber: 3800,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-08T08:30:00Z",
    siteOrDomain: "https://kasurleather.pk",
    termsAppearing: "anywhere",
  },
  {
    id: 62,
    title: "Miami Beach Art Deco District",
    text: "Tour of Miami Beach's iconic Art Deco architecture, colorful buildings, and historic preservation efforts.",
    associatedNumber: 15400,
    language: "english",
    region: "US",
    lastUpdate: "2026-02-01T09:20:00Z",
    siteOrDomain: "https://miamiartdeco.com",
    termsAppearing: "URL",
  },
  {
    id: 63,
    title: "Bath Roman Baths Experience",
    text: "Step back in time at the ancient Roman Baths in Bath, featuring thermal springs and Roman artifacts.",
    associatedNumber: 11300,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-28T11:40:00Z",
    siteOrDomain: "https://bathromanbaths.co.uk",
    termsAppearing: "text",
  },
  {
    id: 64,
    title: "وہاڑی کی گندم کی کاشت",
    text: "ضلع وہاڑی میں گندم کی کاشت، پیداوار اور زرعی تکنیک کی تفصیلی معلومات۔",
    associatedNumber: 1050,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-07T14:15:00Z",
    siteOrDomain: "https://vehariwheat.pk",
    termsAppearing: "title",
  },
  {
    id: 65,
    title: "Las Vegas Entertainment Shows 2026",
    text: "Complete guide to Las Vegas shows including Cirque du Soleil, concerts, magic acts, and comedy performances.",
    associatedNumber: 34800,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-30T12:55:00Z",
    siteOrDomain: "https://vegasshows.com",
    termsAppearing: "anywhere",
  },
  {
    id: 66,
    title: "Durham Castle University College",
    text: "Information about Durham Castle, a UNESCO site housing University College Durham since 1832.",
    associatedNumber: 7200,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-31T08:25:00Z",
    siteOrDomain: "https://durhamcastle.co.uk",
    termsAppearing: "URL",
  },
  {
    id: 67,
    title: "اوکاڑہ کی فرنیچر انڈسٹری",
    text: "اوکاڑہ کی لکڑی کے فرنیچر کی صنعت، کاریگری اور مارکیٹ کی معلومات۔",
    associatedNumber: 2150,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-06T12:40:00Z",
    siteOrDomain: "https://okarafurniture.pk",
    termsAppearing: "text",
  },
  {
    id: 68,
    title: "Detroit Automotive Industry Revival",
    text: "Analysis of Detroit's automotive industry transformation and the rise of electric vehicle manufacturing.",
    associatedNumber: 18700,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-29T10:10:00Z",
    siteOrDomain: "https://detroitauto.com",
    termsAppearing: "title",
  },
  {
    id: 69,
    title: "Stratford-upon-Avon Shakespeare Sites",
    text: "Visit Shakespeare's birthplace and other historic locations in Stratford-upon-Avon celebrating the Bard's legacy.",
    associatedNumber: 9400,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-27T13:45:00Z",
    siteOrDomain: "https://shakespearestratford.co.uk",
    termsAppearing: "anywhere",
  },
  {
    id: 70,
    title: "چکوال کی نمک کی کانیں",
    text: "چکوال کے علاقے میں نمک کی کانوں، خیوڑہ نمک کی کان اور نمک کی پیداوار کی معلومات۔",
    associatedNumber: 1730,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-05T10:20:00Z",
    siteOrDomain: "https://chakwalsalt.pk",
    termsAppearing: "URL",
  },
  {
    id: 71,
    title: "Phoenix Desert Hiking Trails",
    text: "Best hiking trails in Phoenix area including Camelback Mountain, Papago Park, and South Mountain.",
    associatedNumber: 7600,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-31T11:30:00Z",
    siteOrDomain: "https://phoenixhiking.com",
    termsAppearing: "text",
  },
  {
    id: 72,
    title: "Winchester Historic Walking Tours",
    text: "Guided walking tours through Winchester's medieval streets, cathedral, and King Arthur's Round Table.",
    associatedNumber: 5400,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-26T09:55:00Z",
    siteOrDomain: "https://winchestertours.co.uk",
    termsAppearing: "title",
  },
  {
    id: 73,
    title: "حافظ آباد کی ٹیکسٹائل ملیں",
    text: "حافظ آباد کی ٹیکسٹائل ملوں کی صنعت، کپڑے کی تیاری اور برآمد کی معلومات۔",
    associatedNumber: 1880,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-04T15:35:00Z",
    siteOrDomain: "https://hafizabadtextile.pk",
    termsAppearing: "anywhere",
  },
  {
    id: 74,
    title: "San Diego Zoo Wildlife Conservation",
    text: "Explore San Diego Zoo's world-class animal exhibits and conservation programs protecting endangered species.",
    associatedNumber: 21300,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-30T08:40:00Z",
    siteOrDomain: "https://sandiegozoo.com",
    termsAppearing: "URL",
  },
  {
    id: 75,
    title: "Coventry Cathedral Modern Architecture",
    text: "The story of Coventry Cathedral's destruction and its modern architectural rebirth as a symbol of peace.",
    associatedNumber: 6100,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-29T12:20:00Z",
    siteOrDomain: "https://coventrycathedral.co.uk",
    termsAppearing: "text",
  },
  {
    id: 76,
    title: "منڈی بہاءالدین کے باغات",
    text: "منڈی بہاءالدین کے باغات، سنگترے کی پیداوار اور باغبانی کی صنعت کی معلومات۔",
    associatedNumber: 1240,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-03T11:05:00Z",
    siteOrDomain: "https://mandiorchards.pk",
    termsAppearing: "title",
  },
  {
    id: 77,
    title: "Minneapolis Lakes and Parks System",
    text: "Discover Minneapolis's extensive chain of lakes and parks perfect for outdoor activities year-round.",
    associatedNumber: 8900,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-28T14:50:00Z",
    siteOrDomain: "https://minneapolisparks.com",
    termsAppearing: "anywhere",
  },
  {
    id: 78,
    title: "Cambridge Punting on River Cam",
    text: "Experience the traditional Cambridge activity of punting along the River Cam past historic college backs.",
    associatedNumber: 10700,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-31T10:10:00Z",
    siteOrDomain: "https://cambridgepunting.co.uk",
    termsAppearing: "URL",
  },
  {
    id: 79,
    title: "نارووال کی دفاعی صنعت",
    text: "نارووال کی دفاعی صنعت، ہتھیاروں کی تیاری اور فوجی تنصیبات کی معلومات۔",
    associatedNumber: 2920,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-02T09:45:00Z",
    siteOrDomain: "https://narowaldefense.pk",
    termsAppearing: "text",
  },
  {
    id: 80,
    title: "Atlanta Civil Rights History Trail",
    text: "Tour Atlanta's significant civil rights landmarks including Martin Luther King Jr. National Historic Site.",
    associatedNumber: 14200,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-27T07:55:00Z",
    siteOrDomain: "https://atlantacivilrights.com",
    termsAppearing: "title",
  },
  {
    id: 81,
    title: "Exeter Historic Quayside",
    text: "Explore Exeter's beautifully restored historic quayside with cafes, shops, and river cruises.",
    associatedNumber: 4700,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-30T13:30:00Z",
    siteOrDomain: "https://exeterquay.co.uk",
    termsAppearing: "anywhere",
  },
  {
    id: 82,
    title: "پاکپتن کے صوفی بزرگ",
    text: "پاکپتن شریف کے صوفی بزرگ، بابا فرید کی درگاہ اور عرس کی تفصیل۔",
    associatedNumber: 2380,
    language: "urdu",
    region: "PK",
    lastUpdate: "2026-01-01T13:20:00Z",
    siteOrDomain: "https://pakpattansufi.pk",
    termsAppearing: "URL",
  },
  {
    id: 83,
    title: "Cleveland Rock and Roll Hall of Fame",
    text: "Visit the iconic Rock and Roll Hall of Fame featuring legendary musicians, instruments, and memorabilia.",
    associatedNumber: 16800,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-29T11:05:00Z",
    siteOrDomain: "https://rockhall.com",
    termsAppearing: "text",
  },
  {
    id: 84,
    title: "Gloucester Docks Waterfront",
    text: "Gloucester's revitalized Victorian docks featuring museums, restaurants, and waterfront attractions.",
    associatedNumber: 5800,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-26T11:45:00Z",
    siteOrDomain: "https://gloucesterdocks.co.uk",
    termsAppearing: "title",
  },
  {
    id: 85,
    title: "لاڑکانہ کی شوگر ملیں",
    text: "لاڑکانہ کی چینی کی صنعت، گنے کی کاشت اور شوگر ملوں کی معلومات۔",
    associatedNumber: 1570,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-31T10:50:00Z",
    siteOrDomain: "https://larkanasugar.pk",
    termsAppearing: "anywhere",
  },
  {
    id: 86,
    title: "Honolulu Beach Activities Guide",
    text: "Complete guide to Waikiki Beach and other Honolulu beaches with surfing, snorkeling, and water sports.",
    associatedNumber: 19800,
    language: "english",
    region: "US",
    lastUpdate: "2026-02-01T07:15:00Z",
    siteOrDomain: "https://honolulubeaches.com",
    termsAppearing: "URL",
  },
  {
    id: 87,
    title: "Lincoln Cathedral Architecture",
    text: "Architectural marvel of Lincoln Cathedral, one of Europe's finest Gothic buildings with stunning views.",
    associatedNumber: 7900,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-31T09:35:00Z",
    siteOrDomain: "https://lincolncathedral.co.uk",
    termsAppearing: "text",
  },
  {
    id: 88,
    title: "رحیم یار خان کے کھجور",
    text: "رحیم یار خان میں کھجور کی کاشت، مختلف اقسام اور کھجور کی برآمد کی معلومات۔",
    associatedNumber: 1410,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-30T15:25:00Z",
    siteOrDomain: "https://rahimyardates.pk",
    termsAppearing: "title",
  },
  {
    id: 89,
    title: "New Orleans Jazz Festival Guide",
    text: "Everything about the New Orleans Jazz & Heritage Festival including lineup, schedule, and local food.",
    associatedNumber: 24500,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-28T12:30:00Z",
    siteOrDomain: "https://nojazzfest.com",
    termsAppearing: "anywhere",
  },
  {
    id: 90,
    title: "Worcester Cathedral Choir Performances",
    text: "Schedule of Worcester Cathedral's renowned choir performances and evensong services.",
    associatedNumber: 4200,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-27T14:10:00Z",
    siteOrDomain: "https://worcestercathedral.co.uk",
    termsAppearing: "URL",
  },
  {
    id: 91,
    title: "خوشاب کے تیل کے کنوؤں",
    text: "خوشاب میں تیل اور گیس کی دریافت، کنوؤں کی کھدائی اور توانائی کی پیداوار۔",
    associatedNumber: 3650,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-29T08:40:00Z",
    siteOrDomain: "https://khushaboil.pk",
    termsAppearing: "text",
  },
  {
    id: 92,
    title: "Pittsburgh Bridges Engineering Marvel",
    text: "Explore Pittsburgh's 446 bridges, more than any other city, and their architectural significance.",
    associatedNumber: 11600,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-30T10:45:00Z",
    siteOrDomain: "https://pittsburghbridges.com",
    termsAppearing: "title",
  },
  {
    id: 93,
    title: "Salisbury Stonehenge Day Trips",
    text: "Plan your visit to Stonehenge from Salisbury including transport options and guided tour information.",
    associatedNumber: 13400,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-29T08:50:00Z",
    siteOrDomain: "https://salisburystonehenge.co.uk",
    termsAppearing: "anywhere",
  },
  {
    id: 94,
    title: "میانوالی کی نمک کی کانیں",
    text: "میانوالی کے قریب نمک کی کانیں، کلر کہر جھیل اور سیاحتی مقامات کی معلومات۔",
    associatedNumber: 1820,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-28T12:15:00Z",
    siteOrDomain: "https://mianwalisalt.pk",
    termsAppearing: "URL",
  },
  {
    id: 95,
    title: "Cincinnati Chili Restaurants Guide",
    text: "The unique Cincinnati-style chili served over spaghetti at famous local parlors like Skyline and Gold Star.",
    associatedNumber: 6400,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-31T13:25:00Z",
    siteOrDomain: "https://cincinnatichili.com",
    termsAppearing: "text",
  },
  {
    id: 96,
    title: "Carlisle Castle Border History",
    text: "Medieval Carlisle Castle's role in border conflicts between UK and Scotland through the centuries.",
    associatedNumber: 5100,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-26T10:20:00Z",
    siteOrDomain: "https://carlislecastle.co.uk",
    termsAppearing: "title",
  },
  {
    id: 97,
    title: "ڈیرہ غازی خان کی گیس کے ذخائر",
    text: "ڈیرہ غازی خان میں قدرتی گیس کے ذخائر، پیداوار اور سپلائی کی معلومات۔",
    associatedNumber: 2750,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-27T14:55:00Z",
    siteOrDomain: "https://dgkhangas.pk",
    termsAppearing: "anywhere",
  },
  {
    id: 98,
    title: "Kansas City BBQ Masters",
    text: "Kansas City's legendary barbecue tradition with the best smokehouses and BBQ competitions.",
    associatedNumber: 9100,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-27T11:40:00Z",
    siteOrDomain: "https://kcbbq.com",
    termsAppearing: "URL",
  },
  {
    id: 99,
    title: "Peterborough Cathedral History",
    text: "Visit the magnificent Peterborough Cathedral, burial place of Catherine of Aragon and Mary Queen of Scots.",
    associatedNumber: 6700,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-30T12:05:00Z",
    siteOrDomain: "https://peterboroughcathedral.co.uk",
    termsAppearing: "text",
  },
  {
    id: 100,
    title: "لیہ کی زراعت اور آبپاشی",
    text: "ضلع لیہ میں زراعت، آبپاشی کا نظام اور فصلوں کی کاشت کی تفصیل۔",
    associatedNumber: 990,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-26T09:30:00Z",
    siteOrDomain: "https://laiahirrigation.pk",
    termsAppearing: "title",
  },
  {
    id: 101,
    title: "Charleston Historic District Tours",
    text: "Walking tours through Charleston's preserved antebellum architecture and historic plantations.",
    associatedNumber: 12800,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-29T09:15:00Z",
    siteOrDomain: "https://charlestonhistoric.com",
    termsAppearing: "anywhere",
  },
  {
    id: 102,
    title: "Preston Market Shopping Experience",
    text: "Explore the covered Victorian market in Preston with fresh produce, crafts, and local specialties.",
    associatedNumber: 3900,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-28T13:45:00Z",
    siteOrDomain: "https://prestonmarket.co.uk",
    termsAppearing: "URL",
  },
  {
    id: 103,
    title: "نوشہرہ کی چینی ملیں",
    text: "نوشہرہ کی شوگر انڈسٹری، گنے کی کاشت اور چینی کی پیداوار کی معلومات۔",
    associatedNumber: 1630,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-25T11:45:00Z",
    siteOrDomain: "https://nausherasugar.pk",
    termsAppearing: "text",
  },
  {
    id: 104,
    title: "Milwaukee Brewery Tours",
    text: "Tour Milwaukee's famous breweries including Miller, Pabst, and craft beer establishments.",
    associatedNumber: 7800,
    language: "english",
    region: "US",
    lastUpdate: "2026-02-01T08:20:00Z",
    siteOrDomain: "https://milwaukeebrewery.com",
    termsAppearing: "title",
  },
  {
    id: 105,
    title: "Ipswich Waterfront Development",
    text: "Modern waterfront regeneration in Ipswich with marina, restaurants, and cultural venues.",
    associatedNumber: 5600,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-31T11:20:00Z",
    siteOrDomain: "https://ipswichwater front.co.uk",
    termsAppearing: "anywhere",
  },
  {
    id: 106,
    title: "اٹک کا تیل اور گیس",
    text: "ضلع اٹک میں تیل اور گیس کی دریافت، کمپنیاں اور پیداوار کی معلومات۔",
    associatedNumber: 4100,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-24T15:10:00Z",
    siteOrDomain: "https://attockoilgas.pk",
    termsAppearing: "URL",
  },
  {
    id: 107,
    title: "Albuquerque Balloon Fiesta",
    text: "World's largest hot air balloon festival in Albuquerque with hundreds of colorful balloons.",
    associatedNumber: 18400,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-28T10:35:00Z",
    siteOrDomain: "https://balloonfiesta.com",
    termsAppearing: "text",
  },
  {
    id: 108,
    title: "Blackpool Tower Entertainment",
    text: "Visit Blackpool Tower's attractions including the ballroom, circus, and spectacular views.",
    associatedNumber: 11900,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-30T14:40:00Z",
    siteOrDomain: "https://blackpooltower.co.uk",
    termsAppearing: "title",
  },
  {
    id: 109,
    title: "چارسدہ کی تاریخ",
    text: "چارسدہ کی قدیم تہذیب، گندھارا کلچر اور تاریخی آثار کی معلومات۔",
    associatedNumber: 1350,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-23T08:25:00Z",
    siteOrDomain: "https://charsa ddahistory.pk",
    termsAppearing: "anywhere",
  },
  {
    id: 110,
    title: "Louisville Kentucky Derby Experience",
    text: "Everything about the Kentucky Derby including Churchill Downs tours, betting, and derby traditions.",
    associatedNumber: 22700,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-27T12:50:00Z",
    siteOrDomain: "https://kentuckyderby.com",
    termsAppearing: "URL",
  },
  {
    id: 111,
    title: "Hull Maritime Museum",
    text: "Explore Hull's rich maritime heritage at this museum showcasing fishing and whaling history.",
    associatedNumber: 4300,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-29T10:55:00Z",
    siteOrDomain: "https://hullmaritime.co.uk",
    termsAppearing: "text",
  },
  {
    id: 112,
    title: "کوہاٹ کی صنعت",
    text: "کوہاٹ کی صنعتی ترقی، سیمنٹ فیکٹریاں اور دیگر صنعتوں کی معلومات۔",
    associatedNumber: 2480,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-22T13:40:00Z",
    siteOrDomain: "https://kohatindustry.pk",
    termsAppearing: "title",
  },
  {
    id: 113,
    title: "Tucson Desert Museum",
    text: "Arizona-Sonora Desert Museum combining zoo, botanical garden, and natural history museum.",
    associatedNumber: 9600,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-31T09:30:00Z",
    siteOrDomain: "https://tucsondesertmuseum.com",
    termsAppearing: "anywhere",
  },
  {
    id: 114,
    title: "Sunderland Bridges and Heritage",
    text: "Tour of Sunderland's iconic bridges including Wearmouth Bridge and the city's shipbuilding history.",
    associatedNumber: 5900,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-26T12:30:00Z",
    siteOrDomain: "https://sunderlandbridges.co.uk",
    termsAppearing: "URL",
  },
  {
    id: 115,
    title: "بھکر کی کھجوروں کی کاشت",
    text: "ضلع بھکر میں کھجور کی کاشت، اقسام اور برآمد کی صنعت کی معلومات۔",
    associatedNumber: 1190,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-21T10:05:00Z",
    siteOrDomain: "https://bhakkardates.pk",
    termsAppearing: "text",
  },
  {
    id: 116,
    title: "El Paso Border Culture",
    text: "Explore the unique blend of American and Mexican cultures in El Paso's border community.",
    associatedNumber: 8200,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-30T11:45:00Z",
    siteOrDomain: "https://elpasaculture.com",
    termsAppearing: "title",
  },
  {
    id: 117,
    title: "Stoke-on-Trent Pottery Heritage",
    text: "Discover Stoke-on-Trent's world-famous pottery industry at ceramics museums and working potteries.",
    associatedNumber: 6500,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-29T13:55:00Z",
    siteOrDomain: "https://stokepottery.co.uk",
    termsAppearing: "anywhere",
  },
  {
    id: 118,
    title: "ٹوبہ ٹیک سنگھ کی زراعت",
    text: "ٹوبہ ٹیک سنگھ کی زرعی صنعت، کپاس اور گندم کی کاشت کی معلومات۔",
    associatedNumber: 1470,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-20T14:20:00Z",
    siteOrDomain: "https://tobafarming.pk",
    termsAppearing: "URL",
  },
  {
    id: 119,
    title: "Memphis Beale Street Blues Clubs",
    text: "Guide to historic Beale Street's blues clubs, live music venues, and Memphis soul food.",
    associatedNumber: 10500,
    language: "english",
    region: "US",
    lastUpdate: "2026-02-01T07:50:00Z",
    siteOrDomain: "https://bealestreetblues.com",
    termsAppearing: "text",
  },
  {
    id: 120,
    title: "Reading Festival Music Lineup",
    text: "Annual Reading Festival featuring top rock, indie, and alternative music acts and camping information.",
    associatedNumber: 17600,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-31T12:10:00Z",
    siteOrDomain: "https://readingfestival.co.uk",
    termsAppearing: "title",
  },
  {
    id: 121,
    title: "مظفرگڑھ کی کھجور",
    text: "مظفرگڑھ کے کھجور کے باغات، کاشت اور برآمد کی صنعت کی تفصیل۔",
    associatedNumber: 1780,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-19T11:35:00Z",
    siteOrDomain: "https://muzaffargardates.pk",
    termsAppearing: "anywhere",
  },
  {
    id: 122,
    title: "Oklahoma City National Memorial",
    text: "Visit the moving Oklahoma City National Memorial honoring victims of the 1995 bombing.",
    associatedNumber: 7100,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-28T09:25:00Z",
    siteOrDomain: "https://oklahomamemorial.com",
    termsAppearing: "URL",
  },
  {
    id: 123,
    title: "Bournemouth Beach Activities",
    text: "Seven miles of golden beaches in Bournemouth with water sports, beach huts, and pier attractions.",
    associatedNumber: 12100,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-30T08:15:00Z",
    siteOrDomain: "https://bournemouthbeach.co.uk",
    termsAppearing: "text",
  },
  {
    id: 124,
    title: "کراچی کی بندرگاہ",
    text: "کراچی کی بندرگاہ کی اہمیت، تجارت اور شپنگ انڈسٹری کی تفصیلی معلومات۔",
    associatedNumber: 8700,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-18T09:50:00Z",
    siteOrDomain: "https://karachiport.pk",
    termsAppearing: "title",
  },
  {
    id: 125,
    title: "Raleigh Research Triangle Tech Hub",
    text: "Explore Research Triangle Park, one of the largest research parks and tech innovation centers.",
    associatedNumber: 15900,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-27T13:40:00Z",
    siteOrDomain: "https://raleightechpark.com",
    termsAppearing: "anywhere",
  },
  {
    id: 126,
    title: "Luton Airport Shopping Guide",
    text: "Shopping and dining options at London Luton Airport with duty-free and retail information.",
    associatedNumber: 9300,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-29T11:50:00Z",
    siteOrDomain: "https://lutonairport.co.uk",
    termsAppearing: "URL",
  },
  {
    id: 127,
    title: "کوہستان کی وادیاں",
    text: "ضلع کوہستان کی خوبصورت وادیاں، قدرتی مناظر اور سیاحت کی معلومات۔",
    associatedNumber: 2650,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-17T15:15:00Z",
    siteOrDomain: "https://kohistanvalleys.pk",
    termsAppearing: "text",
  },
  {
    id: 128,
    title: "Colorado Springs Garden of the Gods",
    text: "Stunning red rock formations at Garden of the Gods park with hiking trails and rock climbing.",
    associatedNumber: 11400,
    language: "english",
    region: "US",
    lastUpdate: "2026-02-01T10:05:00Z",
    siteOrDomain: "https://gardenofgods.com",
    termsAppearing: "title",
  },
  {
    id: 129,
    title: "Southend-on-Sea Pier Longest in World",
    text: "Walk along Southend Pier, the world's longest pleasure pier extending 1.34 miles into the Thames Estuary.",
    associatedNumber: 8400,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-26T14:25:00Z",
    siteOrDomain: "https://southendpier.co.uk",
    termsAppearing: "anywhere",
  },
  {
    id: 130,
    title: "ژوب کا معدنی وسائل",
    text: "ژوب میں معدنی وسائل کی دریافت، کوئلے کی کانیں اور معدنی صنعت کی معلومات۔",
    associatedNumber: 1920,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-16T12:40:00Z",
    siteOrDomain: "https://zhobminerals.pk",
    termsAppearing: "URL",
  },
  {
    id: 131,
    title: "Omaha Henry Doorly Zoo",
    text: "World-class zoo in Omaha featuring the Desert Dome, largest indoor desert, and aquarium exhibits.",
    associatedNumber: 13200,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-30T12:35:00Z",
    siteOrDomain: "https://omahazo o.com",
    termsAppearing: "text",
  },
  {
    id: 132,
    title: "Middlesbrough Transporter Bridge",
    text: "Historic Transporter Bridge in Middlesbrough, one of only a few remaining worldwide.",
    associatedNumber: 4600,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-31T10:45:00Z",
    siteOrDomain: "https://middlesbroughbridge.co.uk",
    termsAppearing: "title",
  },
  {
    id: 133,
    title: "شکارپور کی تاریخی عمارات",
    text: "شکارپور کی قدیم عمارتیں، تجارتی تاریخ اور تاریخی بازاروں کی معلومات۔",
    associatedNumber: 1260,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-15T10:10:00Z",
    siteOrDomain: "https://shikarpurheritage.pk",
    termsAppearing: "anywhere",
  },
  {
    id: 134,
    title: "Boise Idaho Outdoor Recreation",
    text: "Outdoor activities in Boise including hiking, skiing, rafting, and mountain biking trails.",
    associatedNumber: 6800,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-29T08:55:00Z",
    siteOrDomain: "https://boiseoutdoors.com",
    termsAppearing: "URL",
  },
  {
    id: 135,
    title: "Derby Museum and Art Gallery",
    text: "Discover local history and art collections at Derby Museum including the Bonnie Prince Charlie room.",
    associatedNumber: 3700,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-28T12:20:00Z",
    siteOrDomain: "https://derbymuseum.co.uk",
    termsAppearing: "text",
  },
  {
    id: 136,
    title: "خیرپور کی کھجوریں",
    text: "خیرپور میں کھجور کی کاشت، مشہور اقسام اور برآمد کی صنعت کی تفصیل۔",
    associatedNumber: 1540,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-14T13:55:00Z",
    siteOrDomain: "https://khairpurdates.pk",
    termsAppearing: "title",
  },
  {
    id: 137,
    title: "Richmond Virginia Historic Sites",
    text: "Tour Richmond's Civil War battlefields, historic homes, and Confederate monument sites.",
    associatedNumber: 10900,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-31T11:10:00Z",
    siteOrDomain: "https://richmondhistory.com",
    termsAppearing: "anywhere",
  },
  {
    id: 138,
    title: "Swansea Bay Waterfront",
    text: "Swansea's revitalized waterfront with museums, marina, and stunning views of Swansea Bay.",
    associatedNumber: 7400,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-27T09:30:00Z",
    siteOrDomain: "https://swanseabay.co.uk",
    termsAppearing: "URL",
  },
  {
    id: 139,
    title: "تھرپارکر کا کوئلہ",
    text: "تھرپارکر کی کوئلے کی کانیں، توانائی کی پیداوار اور معاشی اہمیت کی معلومات۔",
    associatedNumber: 5200,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-13T11:25:00Z",
    siteOrDomain: "https://tharcoal.pk",
    termsAppearing: "text",
  },
  {
    id: 140,
    title: "Salt Lake City Temple Square",
    text: "Visit Temple Square, headquarters of the LDS Church with beautiful gardens and historic buildings.",
    associatedNumber: 14700,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-28T14:15:00Z",
    siteOrDomain: "https://templesquare.com",
    termsAppearing: "title",
  },
  {
    id: 141,
    title: "Warwick Castle Medieval Experience",
    text: "Experience medieval life at Warwick Castle with jousting tournaments, dungeons, and historical reenactments.",
    associatedNumber: 16300,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-30T13:50:00Z",
    siteOrDomain: "https://warwickcastle.co.uk",
    termsAppearing: "anywhere",
  },
  {
    id: 142,
    title: "نواب شاہ کی چینی ملیں",
    text: "نواب شاہ کی شوگر انڈسٹری، گنے کی کاشت اور چینی کی پیداوار کی معلومات۔",
    associatedNumber: 1670,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-12T08:50:00Z",
    siteOrDomain: "https://nawabshahsugar.pk",
    termsAppearing: "URL",
  },
  {
    id: 143,
    title: "Hartford Insurance Industry Hub",
    text: "Hartford's role as the insurance capital of America with major companies and financial services.",
    associatedNumber: 19200,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-27T10:40:00Z",
    siteOrDomain: "https://hartfordinsurance.com",
    termsAppearing: "text",
  },
  {
    id: 144,
    title: "Colchester Roman Ruins",
    text: "Britain's oldest recorded town featuring Roman walls, temple ruins, and archaeological museum.",
    associatedNumber: 5200,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-29T12:05:00Z",
    siteOrDomain: "https://colchesterroman.co.uk",
    termsAppearing: "title",
  },
  {
    id: 145,
    title: "سانگھڑ کی زراعت",
    text: "سانگھڑ میں زراعت، فصلوں کی کاشت اور آبپاشی کے نظام کی معلومات۔",
    associatedNumber: 1390,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-11T14:30:00Z",
    siteOrDomain: "https://sangharagriculture.pk",
    termsAppearing: "anywhere",
  },
  {
    id: 146,
    title: "Des Moines State Fair",
    text: "Iowa State Fair in Des Moines featuring agriculture exhibits, carnival rides, and famous food on a stick.",
    associatedNumber: 8700,
    language: "english",
    region: "US",
    lastUpdate: "2026-02-01T09:25:00Z",
    siteOrDomain: "https://iowastatefair.com",
    termsAppearing: "URL",
  },
  {
    id: 147,
    title: "Cheltenham Horse Racing Festival",
    text: "Cheltenham Festival, the premier National Hunt racing event with the Gold Cup and Champion Hurdle.",
    associatedNumber: 21400,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-26T11:15:00Z",
    siteOrDomain: "https://cheltenhamfestival.co.uk",
    termsAppearing: "text",
  },
  {
    id: 148,
    title: "بدین کی چاول کی کاشت",
    text: "بدین میں چاول کی کاشت، اقسام اور برآمد کی صنعت کی تفصیلی معلومات۔",
    associatedNumber: 1810,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-10T12:45:00Z",
    siteOrDomain: "https://badinrice.pk",
    termsAppearing: "title",
  },
  {
    id: 149,
    title: "Providence WaterFire Art Installation",
    text: "WaterFire Providence's unique art installation featuring bonfires on the river with music and performances.",
    associatedNumber: 9800,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-30T07:35:00Z",
    siteOrDomain: "https://waterfireprovidence.com",
    termsAppearing: "anywhere",
  },
  {
    id: 150,
    title: "Hastings Battle Abbey Historic Site",
    text: "Site of the 1066 Battle of Hastings with abbey ruins and interactive exhibits about Norman conquest.",
    associatedNumber: 6900,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-31T13:20:00Z",
    siteOrDomain: "https://battleabbey.co.uk",
    termsAppearing: "URL",
  },
  {
    id: 151,
    title: "میرپور خاص کی کپاس",
    text: "میرپور خاص میں کپاس کی کاشت، پیداوار اور جننگ فیکٹریوں کی معلومات۔",
    associatedNumber: 1510,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-09T10:20:00Z",
    siteOrDomain: "https://mirpurkascotton.pk",
    termsAppearing: "text",
  },
  {
    id: 152,
    title: "Birmingham Alabama Civil Rights Institute",
    text: "Explore the Birmingham Civil Rights Institute documenting the American civil rights movement.",
    associatedNumber: 11700,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-29T13:10:00Z",
    siteOrDomain: "https://birminghamcivilrights.com",
    termsAppearing: "title",
  },
  {
    id: 153,
    title: "Eastbourne Victorian Pier",
    text: "Classic Victorian pier in Eastbourne with amusements, restaurants, and traditional seaside entertainment.",
    associatedNumber: 5500,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-28T10:40:00Z",
    siteOrDomain: "https://eastbournepier.co.uk",
    termsAppearing: "anywhere",
  },
  {
    id: 154,
    title: "ٹنڈو الہٰ یار کے آم",
    text: "ٹنڈو الہٰ یار کے مشہور آم، اقسام اور پھلوں کی کاشت کی معلومات۔",
    associatedNumber: 1280,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-08T15:05:00Z",
    siteOrDomain: "https://tandoallahyarmangoes.pk",
    termsAppearing: "URL",
  },
  {
    id: 155,
    title: "Buffalo Wings Original Restaurants",
    text: "Discover the original Buffalo chicken wing restaurants including Anchor Bar where they were invented.",
    associatedNumber: 7900,
    language: "english",
    region: "US",
    lastUpdate: "2026-02-01T08:45:00Z",
    siteOrDomain: "https://buffalowings.com",
    termsAppearing: "text",
  },
  {
    id: 156,
    title: "Blackburn Cathedral and Market",
    text: "Visit Blackburn Cathedral and explore the historic market town center with shopping and dining.",
    associatedNumber: 4400,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-27T12:25:00Z",
    siteOrDomain: "https://blackburncathedral.co.uk",
    termsAppearing: "title",
  },
  {
    id: 157,
    title: "قمبر شہداد کوٹ کی زراعت",
    text: "قمبر شہداد کوٹ میں فصلوں کی کاشت، کاشتکاری اور زرعی ترقی کی معلومات۔",
    associatedNumber: 1140,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-07T11:40:00Z",
    siteOrDomain: "https://qambaragriculture.pk",
    termsAppearing: "anywhere",
  },
  {
    id: 158,
    title: "Rochester New York Kodak Heritage",
    text: "Rochester's photographic history and Kodak's legacy in the development of modern photography.",
    associatedNumber: 9400,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-30T11:55:00Z",
    siteOrDomain: "https://rochesterkodak.com",
    termsAppearing: "URL",
  },
  {
    id: 159,
    title: "Guildford Castle Grounds",
    text: "Explore Guildford Castle ruins and beautiful grounds with panoramic views over the town.",
    associatedNumber: 3800,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-29T09:40:00Z",
    siteOrDomain: "https://guildfordcastle.co.uk",
    termsAppearing: "text",
  },
  {
    id: 160,
    title: "راجن پور کے کھجور",
    text: "راجن پور میں کھجور کی کاشت، اقسام اور پیداوار کی تفصیلی معلومات۔",
    associatedNumber: 1620,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-06T09:15:00Z",
    siteOrDomain: "https://rajanpurdates.pk",
    termsAppearing: "title",
  },
  {
    id: 161,
    title: "Grand Rapids Art Prize Competition",
    text: "ArtPrize, the world's largest art competition held annually in Grand Rapids, Michigan.",
    associatedNumber: 12600,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-31T12:40:00Z",
    siteOrDomain: "https://artprizegr.com",
    termsAppearing: "anywhere",
  },
  {
    id: 162,
    title: "Torquay English Riviera Resort",
    text: "Torquay's palm-lined beaches, Victorian architecture, and attractions along the English Riviera.",
    associatedNumber: 8100,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-26T13:15:00Z",
    siteOrDomain: "https://torquayriviera.co.uk",
    termsAppearing: "URL",
  },
  {
    id: 163,
    title: "جیکب آباد کی گرمی",
    text: "جیکب آباد کی شدید گرمی، موسم اور آب و ہوا کی معلومات اور تفصیل۔",
    associatedNumber: 890,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-05T14:50:00Z",
    siteOrDomain: "https://jacobabadweather.pk",
    termsAppearing: "text",
  },
  {
    id: 164,
    title: "Akron Rubber Industry History",
    text: "Akron's legacy as the rubber capital with Goodyear, Firestone, and tire manufacturing heritage.",
    associatedNumber: 8800,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-28T08:30:00Z",
    siteOrDomain: "https://akronrubber.com",
    termsAppearing: "title",
  },
  {
    id: 165,
    title: "Grimsby Fish Market Heritage",
    text: "Grimsby's historic fishing industry and fish market, once the world's largest fishing port.",
    associatedNumber: 4900,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-30T10:20:00Z",
    siteOrDomain: "https://grimsbyfishing.co.uk",
    termsAppearing: "anywhere",
  },
  {
    id: 166,
    title: "کشمور کی زراعت",
    text: "کشمور میں زرعی کاشت، آبپاشی اور فصلوں کی پیداوار کی معلومات۔",
    associatedNumber: 1070,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-04T12:30:00Z",
    siteOrDomain: "https://kashmoreagriculture.pk",
    termsAppearing: "URL",
  },
  {
    id: 167,
    title: "Anchorage Northern Lights Tours",
    text: "Best locations and tours to view Aurora Borealis near Anchorage during winter months.",
    associatedNumber: 17800,
    language: "english",
    region: "US",
    lastUpdate: "2026-02-01T06:55:00Z",
    siteOrDomain: "https://anchoragenorthernlights.com",
    termsAppearing: "text",
  },
  {
    id: 168,
    title: "Hereford Cathedral Mappa Mundi",
    text: "View the famous Mappa Mundi medieval world map at Hereford Cathedral's chained library.",
    associatedNumber: 6300,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-29T11:05:00Z",
    siteOrDomain: "https://herefordcathedral.co.uk",
    termsAppearing: "title",
  },
  {
    id: 169,
    title: "شہداد کوٹ کی چاول کی ملیں",
    text: "شہداد کوٹ کی چاول کی صنعت، ملیں اور برآمد کی تفصیلی معلومات۔",
    associatedNumber: 1950,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-03T10:45:00Z",
    siteOrDomain: "https://shahdadkotrice.pk",
    termsAppearing: "anywhere",
  },
  {
    id: 170,
    title: "Toledo Museum of Art Glass Collection",
    text: "World-renowned glass art collection at Toledo Museum including ancient Roman and modern pieces.",
    associatedNumber: 10300,
    language: "english",
    region: "US",
    lastUpdate: "2026-01-27T14:05:00Z",
    siteOrDomain: "https://toledomuseum.com",
    termsAppearing: "URL",
  },
  {
    id: 171,
    title: "Chichester Festival Theatre",
    text: "Chichester Festival Theatre's acclaimed productions and summer season of plays and performances.",
    associatedNumber: 7600,
    language: "english",
    region: "UK",
    lastUpdate: "2026-01-31T09:50:00Z",
    siteOrDomain: "https://chichestertheatre.co.uk",
    termsAppearing: "text",
  },
  {
    id: 172,
    title: "حیدرآباد کے بانجھ",
    text: "حیدرآباد کے بانجھ بازار، ہینڈی کرافٹ اور روایتی صنعتوں کی معلومات۔",
    associatedNumber: 2340,
    language: "urdu",
    region: "PK",
    lastUpdate: "2025-12-02T15:20:00Z",
    siteOrDomain: "https://hyderabadcrafts.pk",
    termsAppearing: "title",
  },
];
// Finding pages
const allTheseWords = document.querySelector("#all");
const exactWordOrPhrase = document.querySelector("#exact");
const anyOfTheseWords = document.querySelector("#any");
const noneOfTheseWords = document.querySelector("#none");
const minRange = document.querySelector("#min");
const maxRange = document.querySelector("#max");
// Narrowing results
const language = document.querySelector("#language");
const region = document.querySelector("#region");
const lastUpdate = document.querySelector("#update");
const siteOrDomain = document.querySelector("#site");
// Search button
const searchButton = document.querySelector("#search");
// Rendering container
const renderingContainer = document.querySelector("#container");

let filteredData = data;

const render = () => {
  let toBeRendered = "";
  filteredData.map((el) => {
    toBeRendered += `<div class="element">
          <p class="site">${el.siteOrDomain}</p>
          <p class="title">${el.title}</p>
          <p class="text">
            ${el.text}
          </p>
          <p class="updated">${el.lastUpdate}</p>
          <p class="region">${el.region}</p>
        </div>`;
  });
  if (toBeRendered.trim() === "") {
    renderingContainer.innerHTML = `<p style="text-align:center">No data found</p>`;
  } else {
    renderingContainer.innerHTML = toBeRendered;
  }
};

// Function for filtering results based on all words
const allTheseWordsFnc = () => {
  return filteredData.filter((el) =>
    el.title.toLowerCase().includes(allTheseWords.value.trim().toLowerCase()),
  );
};
const exactWordOrPhraseFnc = () => {
  return filteredData.filter((el) =>
    el.title
      .toLowerCase()
      .includes(exactWordOrPhrase.value.trim().toLowerCase()),
  );
};
const anyOfTheseWordsFnc = () => {
  return filteredData.filter((el) =>
    el.title.toLowerCase().includes(anyOfTheseWords.value.trim().toLowerCase()),
  );
};
// const noneOfTheseWordsFnc = () => {
//   const val = noneOfTheseWords.value.trim().toLowerCase();
//   return filteredData.filter((el) =>
//     !el.title
//       .toLowerCase()
//       .includes(val),
//   );
// };
 const numbersRangingFromFnc = () => {
   const minValue = Number(minRange.value);
  const maxValue = Number(maxRange.value);
   return filteredData.filter(
    (el) => el.associatedNumber >= minValue && el.associatedNumber <= maxValue,
  );
 };
searchButton.addEventListener("click", () => {
  filteredData = allTheseWordsFnc();
  filteredData = exactWordOrPhraseFnc();
  filteredData = anyOfTheseWordsFnc();
  // filteredData = noneOfTheseWordsFnc();
   if(Number(minRange.value)!=0 && Number(maxRange.value)!=0){
	   filteredData = numbersRangingFromFnc();
   }
  render();
});

render();
